"""DESCRIPTION"""
__title__ = "gppc"
__author__ = "moxxos"
__copyright__ = "Copyright (C) 2022 moxxos"
__short_description__ = "Check OSRS Grand Exchange prices from the command line. Includes module functionality to check and save item price history."
